### ISSUE TITLE
Issue loading inventory items with no name

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#151]
`[18:03:29 INFO]: [SwordCraftOnline] Generating PlayerInventory 19
[18:03:29 ERROR]: [SwordCraftOnline] Attempted to create item , but no coresponding class was found in net.peacefulcraft.sco.items
[18:03:29 WARN]: [SwordCraftOnline] Task #10782 for SwordCraftOnline v1.0 generated an exception
java.lang.RuntimeException: Failed to generate ItemIdentifier with requested scope  Common
        at net.peacefulcraft.sco.items.ItemIdentifier.generateIdentifier(ItemIdentifier.java:176) ~[?:?]
        at net.peacefulcraft.sco.items.ItemIdentifier.generateItem(ItemIdentifier.java:205) ~[?:?]
        at net.peacefulcraft.sco.items.ItemIdentifier.generateItem(ItemIdentifier.java:194) ~[?:?]
        at net.peacefulcraft.sco.inventories.PlayerInventory.lambda$bindInventory$0(PlayerInventory.java:79) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

**Comment by Parsonswy** [comment]
Was their a specific item that doesn't have a name that should have? I don't see one in the database missing a name. There shouldn't be a situation where an item doesn't have a name. If that happens it should throw an exception because that means something is corrupt or the item identifier class is not to spec.

**Comment by BrokenKage** [comment]
This error occurs when I log in. I have not looked further into it yet. It might be an issue with not moving BlockedSlot items over to the new utilityItems package. I saw a similar issue before I added .getDisplayName() abstract to the interface.

**Comment by Parsonswy** [comment]
Alright. If it happens everytime you login I can duplicate the inv and debug. I don't see a bad item in the inv so it might be inserting empty strings somewhere in the generation pipeline.

**Comment by Parsonswy** [comment]
I think it was actually just because the AirItem didn't have a name. (e4d06cf3de450be9145e93e93a27eacf37c309db)
Let me know if it is not fixed, otherwise closing this.
