### ISSUE TITLE
Error when clicking outside of window

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#152]
I suspect SlotType.OUTSIDE is responsible for passing null value.

`[18:04:55 ERROR]: Could not pass event InventoryClickEvent to SwordCraftOnline v1.0
java.lang.NullPointerException: null
        at net.peacefulcraft.sco.inventories.listeners.InventoryListeners.onInventoryClick(InventoryListeners.java:87) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor3184.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-261]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2526) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1135) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

**Comment by Parsonswy** [comment]
I'll have it eat those events. I don't think there is an intuitive way to resolve this/that in that situation, nor does it seem useful.

**Comment by Parsonswy** [comment]
I can't actually reproduce this and the inventory resolves correctly because the area outside the area outside the Inventory is still technically part of the view so even if you click outside it will just give you an `AirItem` and send the click to whatever the main inventory in the transaction is.

Did this possible start happening after a `/reload`? That would probably break it and cause this to happen because of the no `InventoryOpenEvent` for Player inventories work around. You'd need to relog for the plugin to properly grab the inventory.

**Comment by BrokenKage** [comment]
When I `/reload confirm` I always relog. I can look into this event issue.

**Comment by Parsonswy** [comment]
Nvm. It happened when just opening the player inventory, not player inv + container. In this situation the player's inventory counts as the top inventory instead of the bottom. I thought it was the other way around.

I wasn't seeing it happen because I was testing in creative and the listeners ignore creative inventory events.
