### ISSUE TITLE
Boss Bar usage on MMs causing null pointer

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#96]
Causes mythic mob registry to be aborted leaving custom mob in world that cannot be removed by ActiveMob commands.

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.createBossBar(CraftServer.java:1869) ~[patched_1.15.2.jar:git-Paper-253]
at net.peacefulcraft.sco.mythicmobs.adapters.BukkitBossBar.<init>(BukkitBossBar.java:26) ~[?:?]
at net.peacefulcraft.sco.mythicmobs.adapters.BukkitServer.createBossBar(BukkitServer.java:75) ~[?:?]
at net.peacefulcraft.sco.mythicmobs.mobs.MythicMob.getBossBar(MythicMob.java:1225) ~[?:?]
at net.peacefulcraft.sco.mythicmobs.mobs.ActiveMob.<init>(ActiveMob.java:156) ~[?:?]
at net.peacefulcraft.sco.mythicmobs.mobs.MythicMob.spawn(MythicMob.java:828) ~[?:?]
at net.peacefulcraft.sco.mythicmobs.mobs.MobManager.spawnMob(MobManager.java:205) ~[?:?]
at net.peacefulcraft.sco.mythicmobs.mobs.MobManager.spawnMob(MobManager.java:215) ~[?:?]
at net.peacefulcraft.sco.mythicmobs.mobs.bosses.BossWarden.spawn(BossWarden.java:45) ~[?:?]

**Comment by BrokenKage** [comment]
Resolved. Converted AbstractBossBar calls to Bukkit Boss Bar
